### ISSUE TITLE
请教个问题

### ISSUE THREAD

**Issue by meimosor** [kuschzzp/muses-service-oauth2#2]
大佬，自定义UserDetailsService和CustomeAuthencationProvider后，在Spring Authorization Server需要做什么处理，才能使自定义的UserDetailsService生效？

**Comment by kuschzzp** [comment]
@meimosor 没太理解你的意思，自定义完UserDetailsService注册成bean就行了呀，你有示例代码么？我可以调调看

**Comment by meimosor** [comment]
方便留个联系方式不，我直接发你

**Comment by meimosor** [comment]
> @meimosor 没太理解你的意思，自定义完UserDetailsService注册成bean就行了呀，你有示例代码么？我可以调调看
大佬，能不能加个示例，用户认证时的参数可以传入多个。现在默认的loadUserByUsername只能传入一个属性
![image](https://user-images.githubusercontent.com/31975932/211755706-d71b9e29-466f-480e-9e25-3bb3c99c027e.png)

**Comment by kuschzzp** [comment]
你是想在登录时，输入账号密码的同时再输入一个 tenantName？然后查询用户的时候根据账号和tenantName去查？

**Comment by meimosor** [comment]
> 你是想在登录时，输入账号密码的同时再输入一个 tenantName？然后查询用户的时候根据账号和tenantName去查？

是的，这块在Spring Authorization Server 1.0版本里面怎么实现呢

**Comment by kuschzzp** [comment]
这块儿和Spring Authorization Server没关系吧，还是springsecurity的范围的，我也调了一下，见：
https://github.com/kuschzzp/authorization-server-debug/blob/81d546fb5cb2843fc2345005c4b0b9fbb16dd495/src/main/java/com/goodcol/muses/filter/MyDaoAuthenticationProvider.java#L19

https://github.com/kuschzzp/authorization-server-debug/blob/81d546fb5cb2843fc2345005c4b0b9fbb16dd495/src/main/java/com/goodcol/muses/filter/MyWebAuthenticationDetails.java#L12

https://github.com/kuschzzp/authorization-server-debug/blob/81d546fb5cb2843fc2345005c4b0b9fbb16dd495/src/main/java/com/goodcol/muses/filter/MyWebAuthenticationDetailsSource.java#L16

https://github.com/kuschzzp/authorization-server-debug/blob/81d546fb5cb2843fc2345005c4b0b9fbb16dd495/src/main/java/com/goodcol/muses/configurations/DefaultSecurityConfig.java#L30-L33

https://github.com/kuschzzp/authorization-server-debug/blob/81d546fb5cb2843fc2345005c4b0b9fbb16dd495/src/main/resources/templates/login.html#L90
